#version: "3.8"

services:
  backend:
    image: masungil/add-app-backend:latest
    container_name: backend
    networks:
      - app-network

  nginx:
    image: masungil/add-app-frontend:latest
    container_name: vue-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
